# Generated by Django 4.2.5 on 2023-10-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lagoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDeLaLaguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('record', 'Record'), ('visit', 'Visit')], max_length=10)),
                ('todo_bien', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('dotacion_incompleta', models.BooleanField(default=False)),
                ('nota', models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True)),
                ('comentario', models.TextField(blank=True)),
                ('lagoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lagoon')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='AnotherChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personaldelalaguna')),
            ],
        ),
    ]
