# Generated by Django 4.2.5 on 2023-10-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lagoon_supervisor_personaldelalaguna_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldelalaguna',
            old_name='type',
            new_name='action',
        ),
        migrations.AlterField(
            model_name='personaldelalaguna',
            name='lagoon',
            field=models.CharField(choices=[('lagoon1', 'Lagoon 1'), ('lagoon2', 'Lagoon 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldelalaguna',
            name='nota',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
        migrations.AlterField(
            model_name='personaldelalaguna',
            name='supervisor',
            field=models.CharField(choices=[('supervisor1', 'Supervisor 1'), ('supervisor2', 'Supervisor 2')], max_length=100),
        ),
        migrations.DeleteModel(
            name='AnotherChecklistItem',
        ),
        migrations.DeleteModel(
            name='Lagoon',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
