# Generated by Django 4.2.5 on 2023-10-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_personaldelalaguna_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionLimpiezaDeFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('supervisor', models.CharField(max_length=200)),
                ('lagoon', models.CharField(max_length=200)),
                ('todo_bien', models.BooleanField(default=False, verbose_name='¿Operando todo bien?')),
                ('en_mantencion', models.BooleanField(default=False, verbose_name='En mantención')),
                ('sin_combustible', models.BooleanField(default=False)),
                ('falla_mecanica', models.BooleanField(default=False)),
                ('problemas_en_piolas', models.BooleanField(default=False)),
                ('alarma_de_recalentamiento', models.BooleanField(default=False)),
                ('otro_motor_fuera_de_borda', models.CharField(blank=True, max_length=200)),
                ('motor_fuera_de_borda_comentario', models.TextField(blank=True)),
                ('filtracion_en_cuerpo', models.BooleanField(default=False)),
                ('filtracion_en_union_muro', models.BooleanField(default=False)),
                ('filtracion_en_union_carro', models.BooleanField(default=False)),
                ('filtracion_en_union_Y', models.BooleanField(default=False)),
                ('otro_tipo_de_filtracion', models.CharField(blank=True, max_length=200)),
                ('manguera_comentarios', models.TextField(blank=True)),
                ('bomba_en_mantencion', models.BooleanField(default=False)),
                ('no_funciona_energia', models.BooleanField(default=False)),
                ('no_funciona_electrico', models.BooleanField(default=False)),
                ('otro_bomba', models.CharField(blank=True, max_length=200)),
                ('bomba_comentarios', models.TextField(blank=True)),
                ('no_optima', models.BooleanField(default=False)),
                ('velocidad_excesiva', models.BooleanField(default=False)),
                ('otro_secuencia', models.CharField(blank=True, max_length=200)),
                ('secuencia_comentarios', models.TextField(blank=True)),
                ('cepillos_gastados_antiguo', models.BooleanField(default=False)),
                ('valvula_mal_estado_antiguo', models.BooleanField(default=False)),
                ('plancha_acero_rota', models.BooleanField(default=False)),
                ('ruedas_mal_estado', models.BooleanField(default=False)),
                ('faldon_externo_gastado', models.BooleanField(default=False)),
                ('faldon_interno_gastado', models.BooleanField(default=False)),
                ('otro_carro_antiguo', models.CharField(blank=True, max_length=200)),
                ('carro_antiguo_comentarios', models.TextField(blank=True)),
                ('cepillos_gastados_nuevo', models.BooleanField(default=False)),
                ('gomas_gastadas', models.BooleanField(default=False)),
                ('valvula_mal_estado_nuevo', models.BooleanField(default=False)),
                ('otro_carro_nuevo', models.CharField(blank=True, max_length=200)),
                ('carro_nuevo_comentarios', models.TextField(blank=True)),
                ('nota', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('evaluacion_comentarios', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
