# Generated by Django 4.2.5 on 2023-10-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_operacionlimpiezadefondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laguna',
            fields=[
                ('idLagunas', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Codigo', models.CharField(max_length=255)),
                ('Identificador', models.FloatField()),
                ('Estado', models.BooleanField()),
                ('Rend', models.BooleanField()),
                ('Nombre_Proyecto', models.CharField(max_length=255)),
                ('idplatanus', models.FloatField()),
                ('ranking', models.FloatField()),
                ('idioma', models.CharField(max_length=255)),
                ('mailcontacto', models.EmailField(max_length=254)),
                ('subjectr', models.CharField(max_length=255)),
                ('mailcontacto2', models.EmailField(max_length=254)),
                ('horariocorte', models.TimeField()),
                ('Water_analysis', models.BooleanField()),
                ('Region', models.FloatField()),
            ],
        ),
    ]
