# Generated by Django 4.2.5 on 2023-10-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_laguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laguna',
            name='Codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='Estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='Identificador',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='Nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='Nombre_Proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='Region',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='Rend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='Water_analysis',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='horariocorte',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='idioma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='idplatanus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='mailcontacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='mailcontacto2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='ranking',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='subjectr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
