# Generated by Django 4.2.5 on 2023-10-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_laguna_codigo_alter_laguna_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionlimpiezadefondo',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='main.laguna'),
        ),
        migrations.AlterField(
            model_name='personaldelalaguna',
            name='lagoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='main.laguna'),
        ),
    ]
