# Generated by Django 4.2.5 on 2023-10-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_operacionlimpiezadefondo_lagoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laguna',
            name='idLagunas',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
