# Generated by Django 4.2.5 on 2023-10-13 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_laguna_idlagunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionLimpiezaManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('supervisor', models.CharField(max_length=200)),
                ('todo_bien', models.BooleanField(default=False, verbose_name='¿Operando todo bien?')),
                ('equipamiento_incompleto', models.BooleanField(default=False, verbose_name='Incompleto')),
                ('equipamiento_defectuoso', models.BooleanField(default=False, verbose_name='Defectuoso')),
                ('bomba_en_mantencion', models.BooleanField(default=False, verbose_name='En mantención o reparación')),
                ('no_funciona_energia', models.BooleanField(default=False, verbose_name='No funciona por falta de energía')),
                ('no_funciona_electrico', models.BooleanField(default=False, verbose_name='No funciona por problema eléctrico o mecánico')),
                ('problemas_en_manguera', models.BooleanField(default=False, verbose_name='Problemas en la manguera')),
                ('otro_bomba', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('bomba_comentarios', models.TextField(blank=True, verbose_name='Bomba Limpieza Manual Comentarios')),
                ('no_optima', models.BooleanField(default=False, verbose_name='No óptima')),
                ('otro_secuencia', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('secuencia_comentarios', models.TextField(blank=True, verbose_name='Secuencia de Limpieza Comentarios')),
                ('suciedad_en_uniones', models.BooleanField(default=False, verbose_name='Suciedad en las uniones de liner, arrugas y baches')),
                ('nota', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('evaluacion_comentarios', models.TextField(blank=True)),
                ('lagoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='main.laguna')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
