# Generated by Django 4.2.5 on 2023-10-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_operacionlimpiezamanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionlimpiezamanual',
            name='Equipamiento_comentarios',
            field=models.TextField(blank=True, verbose_name='Equipamiento Comentarios'),
        ),
    ]
