# Generated by Django 4.2.5 on 2023-10-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_operacionlimpiezamanual_equipamiento_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadAguaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_bien', models.BooleanField(default=False, verbose_name='¿Operando todo bien? Sí')),
                ('turbidez_media', models.BooleanField(default=False, verbose_name='Turbidez media')),
                ('sucia', models.BooleanField(default=False, verbose_name='Sucia')),
                ('otro_calidad_salida', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('calidad_salida_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('lecho_saturado', models.BooleanField(default=False, verbose_name='El lecho filtrante está saturado')),
                ('valvulas_no_funcionan', models.BooleanField(default=False, verbose_name='Las válvulas no abren y/o cierran bien')),
                ('filtracion_tuberias', models.BooleanField(default=False, verbose_name='Filtración de tuberías')),
                ('otro_filtro', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('filtro_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('turbidez_baja', models.BooleanField(default=False, verbose_name='Turbidez baja')),
                ('turbidez_media_camara', models.BooleanField(default=False, verbose_name='Turbidez media')),
                ('turbidez_alta', models.BooleanField(default=False, verbose_name='Turbidez alta')),
                ('otro_calidad_camara', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('calidad_camara_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('sensores_no_funcionan', models.BooleanField(default=False, verbose_name='Sensores no funcionan')),
                ('otro_sensores', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('sensores_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('bomba_en_mantencion', models.BooleanField(default=False, verbose_name='En mantención')),
                ('no_funciona_energia_bomba', models.BooleanField(default=False, verbose_name='No funciona por falta de energía')),
                ('no_funciona_electrico_bomba', models.BooleanField(default=False, verbose_name='No funciona por problema eléctrico o mecánico')),
                ('problemas_variador', models.BooleanField(default=False, verbose_name='Problemas variador de frecuencia /Partidor Suave')),
                ('otro_bomba', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('bomba_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('nota', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('evaluacion_comentarios', models.TextField(blank=True)),
            ],
        ),
    ]
