# Generated by Django 4.2.5 on 2023-10-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_calidadaguasalida'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalidadAguaSalida',
            new_name='OperacionFiltro',
        ),
    ]
