# Generated by Django 4.2.5 on 2023-10-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_calidadaguasalida_operacionfiltro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperacionFiltro',
        ),
        migrations.RemoveField(
            model_name='operacionlimpiezamanual',
            name='lagoon',
        ),
        migrations.RemoveField(
            model_name='personaldelalaguna',
            name='lagoon',
        ),
        migrations.DeleteModel(
            name='OperacionLimpiezaDeFondo',
        ),
        migrations.DeleteModel(
            name='OperacionLimpiezaManual',
        ),
        migrations.DeleteModel(
            name='PersonalDeLaLaguna',
        ),
    ]
