# Generated by Django 4.2.5 on 2023-10-13 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_personaldelalaguna_operacionlimpiezamanual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionSistemaDosificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('supervisor', models.CharField(max_length=200)),
                ('todo_bien', models.BooleanField(default=False, verbose_name='¿Operando todo bien? Sí')),
                ('nivel_bajo', models.BooleanField(default=False, verbose_name='Bajo')),
                ('nivel_critico', models.BooleanField(default=False, verbose_name='Crítico')),
                ('nivel_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('bomba_en_mantencion', models.BooleanField(default=False, verbose_name='En mantención')),
                ('bomba_no_funciona_energia', models.BooleanField(default=False, verbose_name='No funciona por falta de energía')),
                ('bomba_no_funciona_electrico', models.BooleanField(default=False, verbose_name='No funciona por problemas eléctrico o mecánico')),
                ('bomba_no_marca_presion', models.BooleanField(default=False, verbose_name='No marca presión')),
                ('otro_bomba', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('bomba_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('filtracion_estanque', models.BooleanField(default=False, verbose_name='Filtración en estanque')),
                ('valvula_corte_dañadas', models.BooleanField(default=False, verbose_name='Vávula de corte dañadas')),
                ('otro_estanque', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('estanque_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('caudal_insuficiente', models.BooleanField(default=False, verbose_name='Insuficiente caudal bomba dosificadora')),
                ('valvulas_tapadas', models.BooleanField(default=False, verbose_name='Válvulas retención tapadas o defectuosas')),
                ('mangueras_incrustaciones', models.BooleanField(default=False, verbose_name='Mangueras o tuberías con incrustaciones')),
                ('venturi_mal_estado', models.BooleanField(default=False, verbose_name='Venturi en mal estado')),
                ('otro_venturi', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('venturi_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('bomba_playa_en_mantencion', models.BooleanField(default=False, verbose_name='En mantención')),
                ('bomba_playa_no_funciona_energia', models.BooleanField(default=False, verbose_name='No funciona por falta de energía')),
                ('bomba_playa_no_funciona_electrico', models.BooleanField(default=False, verbose_name='No funciona por problemas eléctrico o mecánico')),
                ('otro_bomba_playa', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('bomba_playa_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('discordancia_telemetria', models.BooleanField(default=False, verbose_name='Discordancia entre la dosificación por telemetría y la real')),
                ('nota', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('evaluacion_comentarios', models.TextField(blank=True)),
                ('lagoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='main.laguna')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
