# Generated by Django 4.2.5 on 2023-10-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_operacionsistemadosificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionSistemaRecirculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_bien', models.BooleanField(default=False, verbose_name='¿Operando todo bien? Sí')),
                ('bomba_en_mantencion', models.BooleanField(default=False, verbose_name='En mantención')),
                ('no_funciona_energia', models.BooleanField(default=False, verbose_name='No funciona por falta de energía')),
                ('no_funciona_electrico', models.BooleanField(default=False, verbose_name='No funciona por problemas eléctricos o mecánicos')),
                ('otro_bomba', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('bomba_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('inyectores_no_funciona', models.BooleanField(default=False, verbose_name='No funciona')),
                ('caudal_bajo', models.BooleanField(default=False, verbose_name='Caudal bajo')),
                ('faltan_inyectores', models.BooleanField(default=False, verbose_name='Faltan inyectores por instalar')),
                ('otro_inyectores', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('inyectores_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('manifold_no_cierra', models.BooleanField(default=False, verbose_name='No cierra correctamente')),
                ('manifold_filtraciones', models.BooleanField(default=False, verbose_name='Con filtraciones')),
                ('otro_manifold', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('manifold_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('camara_filtraciones', models.BooleanField(default=False, verbose_name='Presenta filtraciones')),
                ('otro_camara', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('camara_comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('nota', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('evaluacion_comentario', models.TextField(blank=True, verbose_name='Comentario')),
            ],
        ),
    ]
