# Generated by Django 4.2.5 on 2023-10-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_operacionsistemarecirculacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionamientoTelemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_bien', models.BooleanField(default=False, verbose_name='¿Operando todo bien? Sí')),
                ('conexion_problemas', models.BooleanField(default=False, verbose_name='Conexión con problemas')),
                ('otro_comunicacion', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('sin_conexion', models.BooleanField(default=False, verbose_name='Sin conexión')),
                ('velocidad_baja', models.BooleanField(default=False, verbose_name='Velocidad baja')),
                ('otro_internet', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('circuito_agua', models.BooleanField(default=False, verbose_name='Circuito eléctrico con agua')),
                ('sensor_temp_danado', models.BooleanField(default=False, verbose_name='Dañado')),
                ('sensor_temp_no_funciona', models.BooleanField(default=False, verbose_name='No funciona')),
                ('sensor_temp_fuera_rango', models.BooleanField(default=False, verbose_name='Fuera de rango')),
                ('otro_sensor_temp', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('sensor_orp_danado', models.BooleanField(default=False, verbose_name='Dañado')),
                ('sensor_orp_no_funciona', models.BooleanField(default=False, verbose_name='No funciona')),
                ('sensor_orp_fuera_rango', models.BooleanField(default=False, verbose_name='Fuera de rango')),
                ('otro_sensor_orp', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('turbidimetro_no_funciona', models.BooleanField(default=False, verbose_name='No funciona')),
                ('turbidimetro_danado', models.BooleanField(default=False, verbose_name='Dañado')),
                ('turbidimetro_fuera_rango', models.BooleanField(default=False, verbose_name='Fuera de rango')),
                ('otro_turbidimetro', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('bomba_potencia_insuficiente', models.BooleanField(default=False, verbose_name='No tiene la potencia necesaria')),
                ('bomba_no_funciona', models.BooleanField(default=False, verbose_name='No funciona')),
                ('otro_bomba', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('pantalla_touch_no_funciona', models.BooleanField(default=False, verbose_name='Pantalla touch no funciona')),
                ('monitor_apagado', models.BooleanField(default=False, verbose_name='Apagado')),
                ('otro_monitor', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('panel_no_energizado', models.BooleanField(default=False, verbose_name='No energizado')),
                ('panel_no_funciona', models.BooleanField(default=False, verbose_name='No funciona')),
                ('otro_panel', models.CharField(blank=True, max_length=200, verbose_name='Otro')),
                ('nota', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('evaluacion_comentario', models.TextField(blank=True, verbose_name='Comentario')),
            ],
        ),
    ]
