# Generated by Django 4.2.5 on 2023-10-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_operacionultrasonido_niveldelalaguna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicionliner',
            name='lagoon',
        ),
        migrations.RemoveField(
            model_name='condicionvisuallaguna',
            name='lagoon',
        ),
        migrations.RemoveField(
            model_name='funcionamientoaguarelleno',
            name='lagoon',
        ),
        migrations.DeleteModel(
            name='FuncionamientoTelemetria',
        ),
        migrations.RemoveField(
            model_name='infraestructura',
            name='lagoon',
        ),
        migrations.RemoveField(
            model_name='medidasdemitigacion',
            name='lagoon',
        ),
        migrations.RemoveField(
            model_name='niveldelalaguna',
            name='lagoon',
        ),
        migrations.RemoveField(
            model_name='operacionfiltro',
            name='lagoon',
        ),
        migrations.RemoveField(
            model_name='operacionlimpiezadefondo',
            name='lagoon',
        ),
        migrations.RemoveField(
            model_name='operacionlimpiezamanual',
            name='lagoon',
        ),
        migrations.RemoveField(
            model_name='operacionsistemadosificacion',
            name='lagoon',
        ),
        migrations.DeleteModel(
            name='OperacionSistemaRecirculacion',
        ),
        migrations.DeleteModel(
            name='OperacionSkimmers',
        ),
        migrations.RemoveField(
            model_name='operacionultrasonido',
            name='lagoon',
        ),
        migrations.DeleteModel(
            name='CondicionLiner',
        ),
        migrations.DeleteModel(
            name='CondicionVisualLaguna',
        ),
        migrations.DeleteModel(
            name='FuncionamientoAguaRelleno',
        ),
        migrations.DeleteModel(
            name='Infraestructura',
        ),
        migrations.DeleteModel(
            name='MedidasDeMitigacion',
        ),
        migrations.DeleteModel(
            name='NivelDeLaLaguna',
        ),
        migrations.DeleteModel(
            name='OperacionFiltro',
        ),
        migrations.DeleteModel(
            name='OperacionLimpiezaDeFondo',
        ),
        migrations.DeleteModel(
            name='OperacionLimpiezaManual',
        ),
        migrations.DeleteModel(
            name='OperacionSistemaDosificacion',
        ),
        migrations.DeleteModel(
            name='OperacionUltrasonido',
        ),
    ]
