# Generated by Django 4.2.5 on 2023-10-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraestructura',
            name='comentarios_muros',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='comentarios_playa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionfiltro',
            name='bomba_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionfiltro',
            name='calidad_camara_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionfiltro',
            name='calidad_salida_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionfiltro',
            name='filtro_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionfiltro',
            name='sensores_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionlimpiezadefondo',
            name='bomba_comentarios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='operacionlimpiezadefondo',
            name='carro_antiguo_comentarios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='operacionlimpiezadefondo',
            name='carro_nuevo_comentarios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='operacionlimpiezadefondo',
            name='manguera_comentarios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='operacionlimpiezadefondo',
            name='motor_fuera_de_borda_comentario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='operacionlimpiezadefondo',
            name='secuencia_comentarios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='operacionlimpiezamanual',
            name='Equipamiento_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Equipamiento Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionlimpiezamanual',
            name='bomba_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bomba Limpieza Manual Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionlimpiezamanual',
            name='secuencia_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secuencia de Limpieza Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionsistemadosificacion',
            name='bomba_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionsistemadosificacion',
            name='bomba_playa_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionsistemadosificacion',
            name='estanque_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionsistemadosificacion',
            name='nivel_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionsistemadosificacion',
            name='venturi_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionsistemarecirculacion',
            name='bomba_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionsistemarecirculacion',
            name='camara_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionsistemarecirculacion',
            name='inyectores_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionsistemarecirculacion',
            name='manifold_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionskimmers',
            name='agua_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionskimmers',
            name='filtro_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionskimmers',
            name='manguera_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='operacionskimmers',
            name='sensores_comentarios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
    ]
