# Generated by Django 4.2.5 on 2023-10-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_operacionlimpiezadefondo_bomba_en_mantencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LagunaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='laguna_images/')),
                ('date', models.DateField()),
                ('selected', models.BooleanField(default=False)),
                ('laguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.laguna')),
            ],
        ),
    ]
