# Generated by Django 4.2.5 on 2023-10-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_lagoondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lagoondetail',
            name='idLagunas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.laguna', verbose_name='Lagoon ID'),
        ),
    ]
