# Generated by Django 4.2.5 on 2023-10-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_lagoondetail_idlagunas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lagoondetail',
            old_name='idLagunas',
            new_name='lagoon',
        ),
        migrations.AlterUniqueTogether(
            name='lagoondetail',
            unique_together={('lagoon', 'date')},
        ),
    ]
