# Generated by Django 4.2.5 on 2023-10-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_idlagunas_lagoondetail_lagoon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lagoondetail',
            old_name='lagoon',
            new_name='idLagunas',
        ),
        migrations.AlterUniqueTogether(
            name='lagoondetail',
            unique_together={('idLagunas', 'date')},
        ),
    ]
