# Generated by Django 4.2.5 on 2023-10-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_lagoon_lagoondetail_idlagunas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laguna',
            name='idplatanus_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
