# Generated by Django 4.2.5 on 2023-10-25 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_laguna_idplatanus_temp_alter_laguna_idplatanus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laguna',
            name='idplatanus',
        ),
    ]
