# Generated by Django 4.2.5 on 2023-10-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_laguna_idplatanus_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laguna',
            name='Identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='Region',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laguna',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
