# Generated by Django 4.2.5 on 2023-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_laguna_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_ap2hi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_cotflo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_fh1lo',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_flo12',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_mb010',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
