# Generated by Django 4.2.5 on 2023-12-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_laguna_stock_cl_ap2hi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laguna_stock',
            old_name='cl_ap2hi',
            new_name='cl_ap2hi_storage',
        ),
        migrations.RenameField(
            model_name='laguna_stock',
            old_name='cl_cotflo',
            new_name='cl_cotflo_storage',
        ),
        migrations.RenameField(
            model_name='laguna_stock',
            old_name='cl_fh1lo',
            new_name='cl_fh1lo_storage',
        ),
        migrations.RenameField(
            model_name='laguna_stock',
            old_name='cl_flo12',
            new_name='cl_flo12_storage',
        ),
        migrations.RenameField(
            model_name='laguna_stock',
            old_name='cl_mb010',
            new_name='cl_mb010_storage',
        ),
        migrations.AddField(
            model_name='laguna_stock',
            name='cl_ap2hi_tank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laguna_stock',
            name='cl_cotflo_tank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laguna_stock',
            name='cl_fh1lo_tank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laguna_stock',
            name='cl_flo12_tank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laguna_stock',
            name='cl_mb010_tank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
