# Generated by Django 4.2.5 on 2023-12-22 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_rename_cl_ap2hi_laguna_stock_cl_ap2hi_storage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_liner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condicionliner')),
                ('condicion_visual_laguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condicionvisuallaguna')),
                ('funcionamiento_agua_relleno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.funcionamientoaguarelleno')),
                ('funcionamiento_telemetria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.funcionamientotelemetria')),
                ('infraestructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.infraestructura')),
                ('medidas_de_mitigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medidasdemitigacion')),
                ('nivel_de_la_laguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.niveldelalaguna')),
                ('operacion_filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operacionfiltro')),
                ('operacion_limpieza_de_fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operacionlimpiezadefondo')),
                ('operacion_limpieza_manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operacionlimpiezamanual')),
                ('operacion_sistema_dosificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operacionsistemadosificacion')),
                ('operacion_sistema_recirculacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operacionsistemarecirculacion')),
                ('operacion_skimmers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operacionskimmers')),
                ('operacion_ultrasonido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operacionultrasonido')),
                ('personal_de_la_laguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personaldelalaguna')),
            ],
        ),
    ]
