# Generated by Django 4.2.5 on 2023-12-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_consolidatedreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsolidatedReport',
        ),
    ]
