# Generated by Django 4.2.5 on 2023-12-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_personaldelalaguna_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldelalaguna',
            name='nota',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
    ]
