# Generated by Django 4.2.5 on 2023-12-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_condicionliner_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lagunaimage',
            name='photo',
            field=models.ImageField(upload_to='upload_to_placeholder'),
        ),
        migrations.CreateModel(
            name='RelevantMatters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('laguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevant_matters', to='main.laguna')),
            ],
            options={
                'unique_together': {('laguna', 'date')},
            },
        ),
    ]
