# Generated by Django 4.2.5 on 2023-12-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='IMOP',
        ),
    ]
