# Generated by Django 4.2.5 on 2023-12-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_imop_generated_id_imop_laguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imop',
            name='laguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.laguna'),
        ),
    ]
