# Generated by Django 4.2.5 on 2023-12-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_imop_laguna'),
    ]

    operations = [
        migrations.AddField(
            model_name='imop',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
