# Generated by Django 4.2.5 on 2023-12-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_imop_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='laguna',
            name='filtroreporte',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
