# Generated by Django 4.2.5 on 2023-12-28 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_supervisorlaguna_supervisor_lagunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivosLaguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadtime', models.CharField(max_length=255)),
                ('ddaDiaLts_AP2', models.CharField(max_length=255)),
                ('ddaDiaLts_FH1', models.CharField(max_length=255)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos_laguna', to='main.laguna')),
            ],
        ),
    ]
