# Generated by Django 4.2.5 on 2023-12-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_aditivoslaguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imop',
            name='last_recomendaciones_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='imop',
            name='last_resumen_ejecutivo_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='imop',
            name='last_temas_pendientes_date',
            field=models.DateField(null=True),
        ),
    ]
