# Generated by Django 5.0 on 2024-02-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_rename_last_recomendaciones_date_imop_recomendaciones_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacionfiltro',
            old_name='evaluacion_comentarios',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='operacionlimpiezadefondo',
            old_name='evaluacion_comentarios',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='operacionlimpiezamanual',
            old_name='evaluacion_comentarios',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='operacionsistemadosificacion',
            old_name='evaluacion_comentarios',
            new_name='comentario',
        ),
    ]
