# Generated by Django 5.0 on 2024-02-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_rename_evaluacion_comentarios_operacionfiltro_comentario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionamientotelemetria',
            old_name='evaluacion_comentario',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='operacionsistemarecirculacion',
            old_name='evaluacion_comentario',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='operacionskimmers',
            old_name='evaluacion_comentario',
            new_name='comentario',
        ),
    ]
