# Generated by Django 5.0 on 2024-02-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_rename_evaluacion_comentario_funcionamientotelemetria_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imop',
            name='var_AP2HI',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='var_FH1LO',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
