# Generated by Django 5.0 on 2024-02-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_imop_var_ap2hi_imop_var_fh1lo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imop',
            name='nota_final',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
