# Generated by Django 5.0 on 2024-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_imop_nota_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='imop',
            name='BC',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='DOS',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='ENV',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='FIL',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='INF',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='LIN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='LVL',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='MC',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='PER',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='REC',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='SKI',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='TEL',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='ULT',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='VISUAL',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imop',
            name='WAT',
            field=models.TextField(null=True),
        ),
    ]
