# Generated by Django 5.0 on 2024-02-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_imop_bc_imop_dos_imop_env_imop_fil_imop_inf_imop_lin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imop',
            name='date',
            field=models.DateField(),
        ),
    ]
