# Generated by Django 5.0.4 on 2024-05-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_imop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_ap2hi_tank',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_cotflo_tank',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_fh1lo_tank',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_flo12_tank',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='laguna_stock',
            name='cl_mb010_tank',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
